/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KoRouteImport } from './routes/ko'
import { Route as FrRouteImport } from './routes/fr'
import { Route as EnRouteImport } from './routes/en'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KoIndexRouteImport } from './routes/ko.index'
import { Route as FrIndexRouteImport } from './routes/fr.index'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as KoSignupRouteImport } from './routes/ko.signup'
import { Route as KoLoginRouteImport } from './routes/ko.login'
import { Route as KoListingsRouteImport } from './routes/ko.listings'
import { Route as KoLandlordsRouteImport } from './routes/ko.landlords'
import { Route as KoContactRouteImport } from './routes/ko.contact'
import { Route as KoChecklistRouteImport } from './routes/ko.checklist'
import { Route as KoApplyRouteImport } from './routes/ko.apply'
import { Route as KoAboutRouteImport } from './routes/ko.about'
import { Route as FrSignupRouteImport } from './routes/fr.signup'
import { Route as FrLoginRouteImport } from './routes/fr.login'
import { Route as FrListingsRouteImport } from './routes/fr.listings'
import { Route as FrLandlordsRouteImport } from './routes/fr.landlords'
import { Route as FrContactRouteImport } from './routes/fr.contact'
import { Route as FrChecklistRouteImport } from './routes/fr.checklist'
import { Route as FrApplyRouteImport } from './routes/fr.apply'
import { Route as FrAboutRouteImport } from './routes/fr.about'
import { Route as EnSignupRouteImport } from './routes/en.signup'
import { Route as EnLoginRouteImport } from './routes/en.login'
import { Route as EnListingsRouteImport } from './routes/en.listings'
import { Route as EnLandlordsRouteImport } from './routes/en.landlords'
import { Route as EnContactRouteImport } from './routes/en.contact'
import { Route as EnChecklistRouteImport } from './routes/en.checklist'
import { Route as EnApplyRouteImport } from './routes/en.apply'
import { Route as EnAboutRouteImport } from './routes/en.about'
import { Route as KoLandlordsRegisterRouteImport } from './routes/ko.landlords.register'
import { Route as KoLandlordsGuideRouteImport } from './routes/ko.landlords.guide'
import { Route as KoContactBoardRouteImport } from './routes/ko.contact.board'
import { Route as FrLandlordsRegisterRouteImport } from './routes/fr.landlords.register'
import { Route as FrLandlordsGuideRouteImport } from './routes/fr.landlords.guide'
import { Route as EnLandlordsRegisterRouteImport } from './routes/en.landlords.register'
import { Route as EnLandlordsGuideRouteImport } from './routes/en.landlords.guide'
import { Route as KoLandlordsRegisterTermsRouteImport } from './routes/ko.landlords.register.terms'
import { Route as KoLandlordsRegisterRoomsRouteImport } from './routes/ko.landlords.register.rooms'
import { Route as KoLandlordsRegisterPropertyRouteImport } from './routes/ko.landlords.register.property'
import { Route as KoLandlordsRegisterPreviewRouteImport } from './routes/ko.landlords.register.preview'
import { Route as KoContactBoardWriteRouteImport } from './routes/ko.contact.board.write'
import { Route as KoContactBoardPostIdRouteImport } from './routes/ko.contact.board.$postId'
import { Route as FrLandlordsRegisterTermsRouteImport } from './routes/fr.landlords.register.terms'
import { Route as FrLandlordsRegisterRoomsRouteImport } from './routes/fr.landlords.register.rooms'
import { Route as FrLandlordsRegisterPropertyRouteImport } from './routes/fr.landlords.register.property'
import { Route as FrLandlordsRegisterPreviewRouteImport } from './routes/fr.landlords.register.preview'
import { Route as EnLandlordsRegisterTermsRouteImport } from './routes/en.landlords.register.terms'
import { Route as EnLandlordsRegisterRoomsRouteImport } from './routes/en.landlords.register.rooms'
import { Route as EnLandlordsRegisterPropertyRouteImport } from './routes/en.landlords.register.property'
import { Route as EnLandlordsRegisterPreviewRouteImport } from './routes/en.landlords.register.preview'

const KoRoute = KoRouteImport.update({
  id: '/ko',
  path: '/ko',
  getParentRoute: () => rootRouteImport,
} as any)
const FrRoute = FrRouteImport.update({
  id: '/fr',
  path: '/fr',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KoIndexRoute = KoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KoRoute,
} as any)
const FrIndexRoute = FrIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FrRoute,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnRoute,
} as any)
const KoSignupRoute = KoSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => KoRoute,
} as any)
const KoLoginRoute = KoLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => KoRoute,
} as any)
const KoListingsRoute = KoListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => KoRoute,
} as any)
const KoLandlordsRoute = KoLandlordsRouteImport.update({
  id: '/landlords',
  path: '/landlords',
  getParentRoute: () => KoRoute,
} as any)
const KoContactRoute = KoContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => KoRoute,
} as any)
const KoChecklistRoute = KoChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => KoRoute,
} as any)
const KoApplyRoute = KoApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => KoRoute,
} as any)
const KoAboutRoute = KoAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => KoRoute,
} as any)
const FrSignupRoute = FrSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => FrRoute,
} as any)
const FrLoginRoute = FrLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => FrRoute,
} as any)
const FrListingsRoute = FrListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => FrRoute,
} as any)
const FrLandlordsRoute = FrLandlordsRouteImport.update({
  id: '/landlords',
  path: '/landlords',
  getParentRoute: () => FrRoute,
} as any)
const FrContactRoute = FrContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => FrRoute,
} as any)
const FrChecklistRoute = FrChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => FrRoute,
} as any)
const FrApplyRoute = FrApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => FrRoute,
} as any)
const FrAboutRoute = FrAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => FrRoute,
} as any)
const EnSignupRoute = EnSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => EnRoute,
} as any)
const EnLoginRoute = EnLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => EnRoute,
} as any)
const EnListingsRoute = EnListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => EnRoute,
} as any)
const EnLandlordsRoute = EnLandlordsRouteImport.update({
  id: '/landlords',
  path: '/landlords',
  getParentRoute: () => EnRoute,
} as any)
const EnContactRoute = EnContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => EnRoute,
} as any)
const EnChecklistRoute = EnChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => EnRoute,
} as any)
const EnApplyRoute = EnApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => EnRoute,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => EnRoute,
} as any)
const KoLandlordsRegisterRoute = KoLandlordsRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => KoLandlordsRoute,
} as any)
const KoLandlordsGuideRoute = KoLandlordsGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => KoLandlordsRoute,
} as any)
const KoContactBoardRoute = KoContactBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => KoContactRoute,
} as any)
const FrLandlordsRegisterRoute = FrLandlordsRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => FrLandlordsRoute,
} as any)
const FrLandlordsGuideRoute = FrLandlordsGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => FrLandlordsRoute,
} as any)
const EnLandlordsRegisterRoute = EnLandlordsRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => EnLandlordsRoute,
} as any)
const EnLandlordsGuideRoute = EnLandlordsGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => EnLandlordsRoute,
} as any)
const KoLandlordsRegisterTermsRoute =
  KoLandlordsRegisterTermsRouteImport.update({
    id: '/terms',
    path: '/terms',
    getParentRoute: () => KoLandlordsRegisterRoute,
  } as any)
const KoLandlordsRegisterRoomsRoute =
  KoLandlordsRegisterRoomsRouteImport.update({
    id: '/rooms',
    path: '/rooms',
    getParentRoute: () => KoLandlordsRegisterRoute,
  } as any)
const KoLandlordsRegisterPropertyRoute =
  KoLandlordsRegisterPropertyRouteImport.update({
    id: '/property',
    path: '/property',
    getParentRoute: () => KoLandlordsRegisterRoute,
  } as any)
const KoLandlordsRegisterPreviewRoute =
  KoLandlordsRegisterPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => KoLandlordsRegisterRoute,
  } as any)
const KoContactBoardWriteRoute = KoContactBoardWriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => KoContactBoardRoute,
} as any)
const KoContactBoardPostIdRoute = KoContactBoardPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => KoContactBoardRoute,
} as any)
const FrLandlordsRegisterTermsRoute =
  FrLandlordsRegisterTermsRouteImport.update({
    id: '/terms',
    path: '/terms',
    getParentRoute: () => FrLandlordsRegisterRoute,
  } as any)
const FrLandlordsRegisterRoomsRoute =
  FrLandlordsRegisterRoomsRouteImport.update({
    id: '/rooms',
    path: '/rooms',
    getParentRoute: () => FrLandlordsRegisterRoute,
  } as any)
const FrLandlordsRegisterPropertyRoute =
  FrLandlordsRegisterPropertyRouteImport.update({
    id: '/property',
    path: '/property',
    getParentRoute: () => FrLandlordsRegisterRoute,
  } as any)
const FrLandlordsRegisterPreviewRoute =
  FrLandlordsRegisterPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => FrLandlordsRegisterRoute,
  } as any)
const EnLandlordsRegisterTermsRoute =
  EnLandlordsRegisterTermsRouteImport.update({
    id: '/terms',
    path: '/terms',
    getParentRoute: () => EnLandlordsRegisterRoute,
  } as any)
const EnLandlordsRegisterRoomsRoute =
  EnLandlordsRegisterRoomsRouteImport.update({
    id: '/rooms',
    path: '/rooms',
    getParentRoute: () => EnLandlordsRegisterRoute,
  } as any)
const EnLandlordsRegisterPropertyRoute =
  EnLandlordsRegisterPropertyRouteImport.update({
    id: '/property',
    path: '/property',
    getParentRoute: () => EnLandlordsRegisterRoute,
  } as any)
const EnLandlordsRegisterPreviewRoute =
  EnLandlordsRegisterPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => EnLandlordsRegisterRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/en': typeof EnRouteWithChildren
  '/fr': typeof FrRouteWithChildren
  '/ko': typeof KoRouteWithChildren
  '/en/about': typeof EnAboutRoute
  '/en/apply': typeof EnApplyRoute
  '/en/checklist': typeof EnChecklistRoute
  '/en/contact': typeof EnContactRoute
  '/en/landlords': typeof EnLandlordsRouteWithChildren
  '/en/listings': typeof EnListingsRoute
  '/en/login': typeof EnLoginRoute
  '/en/signup': typeof EnSignupRoute
  '/fr/about': typeof FrAboutRoute
  '/fr/apply': typeof FrApplyRoute
  '/fr/checklist': typeof FrChecklistRoute
  '/fr/contact': typeof FrContactRoute
  '/fr/landlords': typeof FrLandlordsRouteWithChildren
  '/fr/listings': typeof FrListingsRoute
  '/fr/login': typeof FrLoginRoute
  '/fr/signup': typeof FrSignupRoute
  '/ko/about': typeof KoAboutRoute
  '/ko/apply': typeof KoApplyRoute
  '/ko/checklist': typeof KoChecklistRoute
  '/ko/contact': typeof KoContactRouteWithChildren
  '/ko/landlords': typeof KoLandlordsRouteWithChildren
  '/ko/listings': typeof KoListingsRoute
  '/ko/login': typeof KoLoginRoute
  '/ko/signup': typeof KoSignupRoute
  '/en/': typeof EnIndexRoute
  '/fr/': typeof FrIndexRoute
  '/ko/': typeof KoIndexRoute
  '/en/landlords/guide': typeof EnLandlordsGuideRoute
  '/en/landlords/register': typeof EnLandlordsRegisterRouteWithChildren
  '/fr/landlords/guide': typeof FrLandlordsGuideRoute
  '/fr/landlords/register': typeof FrLandlordsRegisterRouteWithChildren
  '/ko/contact/board': typeof KoContactBoardRouteWithChildren
  '/ko/landlords/guide': typeof KoLandlordsGuideRoute
  '/ko/landlords/register': typeof KoLandlordsRegisterRouteWithChildren
  '/en/landlords/register/preview': typeof EnLandlordsRegisterPreviewRoute
  '/en/landlords/register/property': typeof EnLandlordsRegisterPropertyRoute
  '/en/landlords/register/rooms': typeof EnLandlordsRegisterRoomsRoute
  '/en/landlords/register/terms': typeof EnLandlordsRegisterTermsRoute
  '/fr/landlords/register/preview': typeof FrLandlordsRegisterPreviewRoute
  '/fr/landlords/register/property': typeof FrLandlordsRegisterPropertyRoute
  '/fr/landlords/register/rooms': typeof FrLandlordsRegisterRoomsRoute
  '/fr/landlords/register/terms': typeof FrLandlordsRegisterTermsRoute
  '/ko/contact/board/$postId': typeof KoContactBoardPostIdRoute
  '/ko/contact/board/write': typeof KoContactBoardWriteRoute
  '/ko/landlords/register/preview': typeof KoLandlordsRegisterPreviewRoute
  '/ko/landlords/register/property': typeof KoLandlordsRegisterPropertyRoute
  '/ko/landlords/register/rooms': typeof KoLandlordsRegisterRoomsRoute
  '/ko/landlords/register/terms': typeof KoLandlordsRegisterTermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/en/about': typeof EnAboutRoute
  '/en/apply': typeof EnApplyRoute
  '/en/checklist': typeof EnChecklistRoute
  '/en/contact': typeof EnContactRoute
  '/en/landlords': typeof EnLandlordsRouteWithChildren
  '/en/listings': typeof EnListingsRoute
  '/en/login': typeof EnLoginRoute
  '/en/signup': typeof EnSignupRoute
  '/fr/about': typeof FrAboutRoute
  '/fr/apply': typeof FrApplyRoute
  '/fr/checklist': typeof FrChecklistRoute
  '/fr/contact': typeof FrContactRoute
  '/fr/landlords': typeof FrLandlordsRouteWithChildren
  '/fr/listings': typeof FrListingsRoute
  '/fr/login': typeof FrLoginRoute
  '/fr/signup': typeof FrSignupRoute
  '/ko/about': typeof KoAboutRoute
  '/ko/apply': typeof KoApplyRoute
  '/ko/checklist': typeof KoChecklistRoute
  '/ko/contact': typeof KoContactRouteWithChildren
  '/ko/landlords': typeof KoLandlordsRouteWithChildren
  '/ko/listings': typeof KoListingsRoute
  '/ko/login': typeof KoLoginRoute
  '/ko/signup': typeof KoSignupRoute
  '/en': typeof EnIndexRoute
  '/fr': typeof FrIndexRoute
  '/ko': typeof KoIndexRoute
  '/en/landlords/guide': typeof EnLandlordsGuideRoute
  '/en/landlords/register': typeof EnLandlordsRegisterRouteWithChildren
  '/fr/landlords/guide': typeof FrLandlordsGuideRoute
  '/fr/landlords/register': typeof FrLandlordsRegisterRouteWithChildren
  '/ko/contact/board': typeof KoContactBoardRouteWithChildren
  '/ko/landlords/guide': typeof KoLandlordsGuideRoute
  '/ko/landlords/register': typeof KoLandlordsRegisterRouteWithChildren
  '/en/landlords/register/preview': typeof EnLandlordsRegisterPreviewRoute
  '/en/landlords/register/property': typeof EnLandlordsRegisterPropertyRoute
  '/en/landlords/register/rooms': typeof EnLandlordsRegisterRoomsRoute
  '/en/landlords/register/terms': typeof EnLandlordsRegisterTermsRoute
  '/fr/landlords/register/preview': typeof FrLandlordsRegisterPreviewRoute
  '/fr/landlords/register/property': typeof FrLandlordsRegisterPropertyRoute
  '/fr/landlords/register/rooms': typeof FrLandlordsRegisterRoomsRoute
  '/fr/landlords/register/terms': typeof FrLandlordsRegisterTermsRoute
  '/ko/contact/board/$postId': typeof KoContactBoardPostIdRoute
  '/ko/contact/board/write': typeof KoContactBoardWriteRoute
  '/ko/landlords/register/preview': typeof KoLandlordsRegisterPreviewRoute
  '/ko/landlords/register/property': typeof KoLandlordsRegisterPropertyRoute
  '/ko/landlords/register/rooms': typeof KoLandlordsRegisterRoomsRoute
  '/ko/landlords/register/terms': typeof KoLandlordsRegisterTermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/en': typeof EnRouteWithChildren
  '/fr': typeof FrRouteWithChildren
  '/ko': typeof KoRouteWithChildren
  '/en/about': typeof EnAboutRoute
  '/en/apply': typeof EnApplyRoute
  '/en/checklist': typeof EnChecklistRoute
  '/en/contact': typeof EnContactRoute
  '/en/landlords': typeof EnLandlordsRouteWithChildren
  '/en/listings': typeof EnListingsRoute
  '/en/login': typeof EnLoginRoute
  '/en/signup': typeof EnSignupRoute
  '/fr/about': typeof FrAboutRoute
  '/fr/apply': typeof FrApplyRoute
  '/fr/checklist': typeof FrChecklistRoute
  '/fr/contact': typeof FrContactRoute
  '/fr/landlords': typeof FrLandlordsRouteWithChildren
  '/fr/listings': typeof FrListingsRoute
  '/fr/login': typeof FrLoginRoute
  '/fr/signup': typeof FrSignupRoute
  '/ko/about': typeof KoAboutRoute
  '/ko/apply': typeof KoApplyRoute
  '/ko/checklist': typeof KoChecklistRoute
  '/ko/contact': typeof KoContactRouteWithChildren
  '/ko/landlords': typeof KoLandlordsRouteWithChildren
  '/ko/listings': typeof KoListingsRoute
  '/ko/login': typeof KoLoginRoute
  '/ko/signup': typeof KoSignupRoute
  '/en/': typeof EnIndexRoute
  '/fr/': typeof FrIndexRoute
  '/ko/': typeof KoIndexRoute
  '/en/landlords/guide': typeof EnLandlordsGuideRoute
  '/en/landlords/register': typeof EnLandlordsRegisterRouteWithChildren
  '/fr/landlords/guide': typeof FrLandlordsGuideRoute
  '/fr/landlords/register': typeof FrLandlordsRegisterRouteWithChildren
  '/ko/contact/board': typeof KoContactBoardRouteWithChildren
  '/ko/landlords/guide': typeof KoLandlordsGuideRoute
  '/ko/landlords/register': typeof KoLandlordsRegisterRouteWithChildren
  '/en/landlords/register/preview': typeof EnLandlordsRegisterPreviewRoute
  '/en/landlords/register/property': typeof EnLandlordsRegisterPropertyRoute
  '/en/landlords/register/rooms': typeof EnLandlordsRegisterRoomsRoute
  '/en/landlords/register/terms': typeof EnLandlordsRegisterTermsRoute
  '/fr/landlords/register/preview': typeof FrLandlordsRegisterPreviewRoute
  '/fr/landlords/register/property': typeof FrLandlordsRegisterPropertyRoute
  '/fr/landlords/register/rooms': typeof FrLandlordsRegisterRoomsRoute
  '/fr/landlords/register/terms': typeof FrLandlordsRegisterTermsRoute
  '/ko/contact/board/$postId': typeof KoContactBoardPostIdRoute
  '/ko/contact/board/write': typeof KoContactBoardWriteRoute
  '/ko/landlords/register/preview': typeof KoLandlordsRegisterPreviewRoute
  '/ko/landlords/register/property': typeof KoLandlordsRegisterPropertyRoute
  '/ko/landlords/register/rooms': typeof KoLandlordsRegisterRoomsRoute
  '/ko/landlords/register/terms': typeof KoLandlordsRegisterTermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/en'
    | '/fr'
    | '/ko'
    | '/en/about'
    | '/en/apply'
    | '/en/checklist'
    | '/en/contact'
    | '/en/landlords'
    | '/en/listings'
    | '/en/login'
    | '/en/signup'
    | '/fr/about'
    | '/fr/apply'
    | '/fr/checklist'
    | '/fr/contact'
    | '/fr/landlords'
    | '/fr/listings'
    | '/fr/login'
    | '/fr/signup'
    | '/ko/about'
    | '/ko/apply'
    | '/ko/checklist'
    | '/ko/contact'
    | '/ko/landlords'
    | '/ko/listings'
    | '/ko/login'
    | '/ko/signup'
    | '/en/'
    | '/fr/'
    | '/ko/'
    | '/en/landlords/guide'
    | '/en/landlords/register'
    | '/fr/landlords/guide'
    | '/fr/landlords/register'
    | '/ko/contact/board'
    | '/ko/landlords/guide'
    | '/ko/landlords/register'
    | '/en/landlords/register/preview'
    | '/en/landlords/register/property'
    | '/en/landlords/register/rooms'
    | '/en/landlords/register/terms'
    | '/fr/landlords/register/preview'
    | '/fr/landlords/register/property'
    | '/fr/landlords/register/rooms'
    | '/fr/landlords/register/terms'
    | '/ko/contact/board/$postId'
    | '/ko/contact/board/write'
    | '/ko/landlords/register/preview'
    | '/ko/landlords/register/property'
    | '/ko/landlords/register/rooms'
    | '/ko/landlords/register/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/en/about'
    | '/en/apply'
    | '/en/checklist'
    | '/en/contact'
    | '/en/landlords'
    | '/en/listings'
    | '/en/login'
    | '/en/signup'
    | '/fr/about'
    | '/fr/apply'
    | '/fr/checklist'
    | '/fr/contact'
    | '/fr/landlords'
    | '/fr/listings'
    | '/fr/login'
    | '/fr/signup'
    | '/ko/about'
    | '/ko/apply'
    | '/ko/checklist'
    | '/ko/contact'
    | '/ko/landlords'
    | '/ko/listings'
    | '/ko/login'
    | '/ko/signup'
    | '/en'
    | '/fr'
    | '/ko'
    | '/en/landlords/guide'
    | '/en/landlords/register'
    | '/fr/landlords/guide'
    | '/fr/landlords/register'
    | '/ko/contact/board'
    | '/ko/landlords/guide'
    | '/ko/landlords/register'
    | '/en/landlords/register/preview'
    | '/en/landlords/register/property'
    | '/en/landlords/register/rooms'
    | '/en/landlords/register/terms'
    | '/fr/landlords/register/preview'
    | '/fr/landlords/register/property'
    | '/fr/landlords/register/rooms'
    | '/fr/landlords/register/terms'
    | '/ko/contact/board/$postId'
    | '/ko/contact/board/write'
    | '/ko/landlords/register/preview'
    | '/ko/landlords/register/property'
    | '/ko/landlords/register/rooms'
    | '/ko/landlords/register/terms'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/en'
    | '/fr'
    | '/ko'
    | '/en/about'
    | '/en/apply'
    | '/en/checklist'
    | '/en/contact'
    | '/en/landlords'
    | '/en/listings'
    | '/en/login'
    | '/en/signup'
    | '/fr/about'
    | '/fr/apply'
    | '/fr/checklist'
    | '/fr/contact'
    | '/fr/landlords'
    | '/fr/listings'
    | '/fr/login'
    | '/fr/signup'
    | '/ko/about'
    | '/ko/apply'
    | '/ko/checklist'
    | '/ko/contact'
    | '/ko/landlords'
    | '/ko/listings'
    | '/ko/login'
    | '/ko/signup'
    | '/en/'
    | '/fr/'
    | '/ko/'
    | '/en/landlords/guide'
    | '/en/landlords/register'
    | '/fr/landlords/guide'
    | '/fr/landlords/register'
    | '/ko/contact/board'
    | '/ko/landlords/guide'
    | '/ko/landlords/register'
    | '/en/landlords/register/preview'
    | '/en/landlords/register/property'
    | '/en/landlords/register/rooms'
    | '/en/landlords/register/terms'
    | '/fr/landlords/register/preview'
    | '/fr/landlords/register/property'
    | '/fr/landlords/register/rooms'
    | '/fr/landlords/register/terms'
    | '/ko/contact/board/$postId'
    | '/ko/contact/board/write'
    | '/ko/landlords/register/preview'
    | '/ko/landlords/register/property'
    | '/ko/landlords/register/rooms'
    | '/ko/landlords/register/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  EnRoute: typeof EnRouteWithChildren
  FrRoute: typeof FrRouteWithChildren
  KoRoute: typeof KoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ko': {
      id: '/ko'
      path: '/ko'
      fullPath: '/ko'
      preLoaderRoute: typeof KoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr': {
      id: '/fr'
      path: '/fr'
      fullPath: '/fr'
      preLoaderRoute: typeof FrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/': {
      id: '/ko/'
      path: '/'
      fullPath: '/ko/'
      preLoaderRoute: typeof KoIndexRouteImport
      parentRoute: typeof KoRoute
    }
    '/fr/': {
      id: '/fr/'
      path: '/'
      fullPath: '/fr/'
      preLoaderRoute: typeof FrIndexRouteImport
      parentRoute: typeof FrRoute
    }
    '/en/': {
      id: '/en/'
      path: '/'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/ko/signup': {
      id: '/ko/signup'
      path: '/signup'
      fullPath: '/ko/signup'
      preLoaderRoute: typeof KoSignupRouteImport
      parentRoute: typeof KoRoute
    }
    '/ko/login': {
      id: '/ko/login'
      path: '/login'
      fullPath: '/ko/login'
      preLoaderRoute: typeof KoLoginRouteImport
      parentRoute: typeof KoRoute
    }
    '/ko/listings': {
      id: '/ko/listings'
      path: '/listings'
      fullPath: '/ko/listings'
      preLoaderRoute: typeof KoListingsRouteImport
      parentRoute: typeof KoRoute
    }
    '/ko/landlords': {
      id: '/ko/landlords'
      path: '/landlords'
      fullPath: '/ko/landlords'
      preLoaderRoute: typeof KoLandlordsRouteImport
      parentRoute: typeof KoRoute
    }
    '/ko/contact': {
      id: '/ko/contact'
      path: '/contact'
      fullPath: '/ko/contact'
      preLoaderRoute: typeof KoContactRouteImport
      parentRoute: typeof KoRoute
    }
    '/ko/checklist': {
      id: '/ko/checklist'
      path: '/checklist'
      fullPath: '/ko/checklist'
      preLoaderRoute: typeof KoChecklistRouteImport
      parentRoute: typeof KoRoute
    }
    '/ko/apply': {
      id: '/ko/apply'
      path: '/apply'
      fullPath: '/ko/apply'
      preLoaderRoute: typeof KoApplyRouteImport
      parentRoute: typeof KoRoute
    }
    '/ko/about': {
      id: '/ko/about'
      path: '/about'
      fullPath: '/ko/about'
      preLoaderRoute: typeof KoAboutRouteImport
      parentRoute: typeof KoRoute
    }
    '/fr/signup': {
      id: '/fr/signup'
      path: '/signup'
      fullPath: '/fr/signup'
      preLoaderRoute: typeof FrSignupRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/login': {
      id: '/fr/login'
      path: '/login'
      fullPath: '/fr/login'
      preLoaderRoute: typeof FrLoginRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/listings': {
      id: '/fr/listings'
      path: '/listings'
      fullPath: '/fr/listings'
      preLoaderRoute: typeof FrListingsRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/landlords': {
      id: '/fr/landlords'
      path: '/landlords'
      fullPath: '/fr/landlords'
      preLoaderRoute: typeof FrLandlordsRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/contact': {
      id: '/fr/contact'
      path: '/contact'
      fullPath: '/fr/contact'
      preLoaderRoute: typeof FrContactRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/checklist': {
      id: '/fr/checklist'
      path: '/checklist'
      fullPath: '/fr/checklist'
      preLoaderRoute: typeof FrChecklistRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/apply': {
      id: '/fr/apply'
      path: '/apply'
      fullPath: '/fr/apply'
      preLoaderRoute: typeof FrApplyRouteImport
      parentRoute: typeof FrRoute
    }
    '/fr/about': {
      id: '/fr/about'
      path: '/about'
      fullPath: '/fr/about'
      preLoaderRoute: typeof FrAboutRouteImport
      parentRoute: typeof FrRoute
    }
    '/en/signup': {
      id: '/en/signup'
      path: '/signup'
      fullPath: '/en/signup'
      preLoaderRoute: typeof EnSignupRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/login': {
      id: '/en/login'
      path: '/login'
      fullPath: '/en/login'
      preLoaderRoute: typeof EnLoginRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/listings': {
      id: '/en/listings'
      path: '/listings'
      fullPath: '/en/listings'
      preLoaderRoute: typeof EnListingsRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/landlords': {
      id: '/en/landlords'
      path: '/landlords'
      fullPath: '/en/landlords'
      preLoaderRoute: typeof EnLandlordsRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/contact': {
      id: '/en/contact'
      path: '/contact'
      fullPath: '/en/contact'
      preLoaderRoute: typeof EnContactRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/checklist': {
      id: '/en/checklist'
      path: '/checklist'
      fullPath: '/en/checklist'
      preLoaderRoute: typeof EnChecklistRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/apply': {
      id: '/en/apply'
      path: '/apply'
      fullPath: '/en/apply'
      preLoaderRoute: typeof EnApplyRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/about': {
      id: '/en/about'
      path: '/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof EnRoute
    }
    '/ko/landlords/register': {
      id: '/ko/landlords/register'
      path: '/register'
      fullPath: '/ko/landlords/register'
      preLoaderRoute: typeof KoLandlordsRegisterRouteImport
      parentRoute: typeof KoLandlordsRoute
    }
    '/ko/landlords/guide': {
      id: '/ko/landlords/guide'
      path: '/guide'
      fullPath: '/ko/landlords/guide'
      preLoaderRoute: typeof KoLandlordsGuideRouteImport
      parentRoute: typeof KoLandlordsRoute
    }
    '/ko/contact/board': {
      id: '/ko/contact/board'
      path: '/board'
      fullPath: '/ko/contact/board'
      preLoaderRoute: typeof KoContactBoardRouteImport
      parentRoute: typeof KoContactRoute
    }
    '/fr/landlords/register': {
      id: '/fr/landlords/register'
      path: '/register'
      fullPath: '/fr/landlords/register'
      preLoaderRoute: typeof FrLandlordsRegisterRouteImport
      parentRoute: typeof FrLandlordsRoute
    }
    '/fr/landlords/guide': {
      id: '/fr/landlords/guide'
      path: '/guide'
      fullPath: '/fr/landlords/guide'
      preLoaderRoute: typeof FrLandlordsGuideRouteImport
      parentRoute: typeof FrLandlordsRoute
    }
    '/en/landlords/register': {
      id: '/en/landlords/register'
      path: '/register'
      fullPath: '/en/landlords/register'
      preLoaderRoute: typeof EnLandlordsRegisterRouteImport
      parentRoute: typeof EnLandlordsRoute
    }
    '/en/landlords/guide': {
      id: '/en/landlords/guide'
      path: '/guide'
      fullPath: '/en/landlords/guide'
      preLoaderRoute: typeof EnLandlordsGuideRouteImport
      parentRoute: typeof EnLandlordsRoute
    }
    '/ko/landlords/register/terms': {
      id: '/ko/landlords/register/terms'
      path: '/terms'
      fullPath: '/ko/landlords/register/terms'
      preLoaderRoute: typeof KoLandlordsRegisterTermsRouteImport
      parentRoute: typeof KoLandlordsRegisterRoute
    }
    '/ko/landlords/register/rooms': {
      id: '/ko/landlords/register/rooms'
      path: '/rooms'
      fullPath: '/ko/landlords/register/rooms'
      preLoaderRoute: typeof KoLandlordsRegisterRoomsRouteImport
      parentRoute: typeof KoLandlordsRegisterRoute
    }
    '/ko/landlords/register/property': {
      id: '/ko/landlords/register/property'
      path: '/property'
      fullPath: '/ko/landlords/register/property'
      preLoaderRoute: typeof KoLandlordsRegisterPropertyRouteImport
      parentRoute: typeof KoLandlordsRegisterRoute
    }
    '/ko/landlords/register/preview': {
      id: '/ko/landlords/register/preview'
      path: '/preview'
      fullPath: '/ko/landlords/register/preview'
      preLoaderRoute: typeof KoLandlordsRegisterPreviewRouteImport
      parentRoute: typeof KoLandlordsRegisterRoute
    }
    '/ko/contact/board/write': {
      id: '/ko/contact/board/write'
      path: '/write'
      fullPath: '/ko/contact/board/write'
      preLoaderRoute: typeof KoContactBoardWriteRouteImport
      parentRoute: typeof KoContactBoardRoute
    }
    '/ko/contact/board/$postId': {
      id: '/ko/contact/board/$postId'
      path: '/$postId'
      fullPath: '/ko/contact/board/$postId'
      preLoaderRoute: typeof KoContactBoardPostIdRouteImport
      parentRoute: typeof KoContactBoardRoute
    }
    '/fr/landlords/register/terms': {
      id: '/fr/landlords/register/terms'
      path: '/terms'
      fullPath: '/fr/landlords/register/terms'
      preLoaderRoute: typeof FrLandlordsRegisterTermsRouteImport
      parentRoute: typeof FrLandlordsRegisterRoute
    }
    '/fr/landlords/register/rooms': {
      id: '/fr/landlords/register/rooms'
      path: '/rooms'
      fullPath: '/fr/landlords/register/rooms'
      preLoaderRoute: typeof FrLandlordsRegisterRoomsRouteImport
      parentRoute: typeof FrLandlordsRegisterRoute
    }
    '/fr/landlords/register/property': {
      id: '/fr/landlords/register/property'
      path: '/property'
      fullPath: '/fr/landlords/register/property'
      preLoaderRoute: typeof FrLandlordsRegisterPropertyRouteImport
      parentRoute: typeof FrLandlordsRegisterRoute
    }
    '/fr/landlords/register/preview': {
      id: '/fr/landlords/register/preview'
      path: '/preview'
      fullPath: '/fr/landlords/register/preview'
      preLoaderRoute: typeof FrLandlordsRegisterPreviewRouteImport
      parentRoute: typeof FrLandlordsRegisterRoute
    }
    '/en/landlords/register/terms': {
      id: '/en/landlords/register/terms'
      path: '/terms'
      fullPath: '/en/landlords/register/terms'
      preLoaderRoute: typeof EnLandlordsRegisterTermsRouteImport
      parentRoute: typeof EnLandlordsRegisterRoute
    }
    '/en/landlords/register/rooms': {
      id: '/en/landlords/register/rooms'
      path: '/rooms'
      fullPath: '/en/landlords/register/rooms'
      preLoaderRoute: typeof EnLandlordsRegisterRoomsRouteImport
      parentRoute: typeof EnLandlordsRegisterRoute
    }
    '/en/landlords/register/property': {
      id: '/en/landlords/register/property'
      path: '/property'
      fullPath: '/en/landlords/register/property'
      preLoaderRoute: typeof EnLandlordsRegisterPropertyRouteImport
      parentRoute: typeof EnLandlordsRegisterRoute
    }
    '/en/landlords/register/preview': {
      id: '/en/landlords/register/preview'
      path: '/preview'
      fullPath: '/en/landlords/register/preview'
      preLoaderRoute: typeof EnLandlordsRegisterPreviewRouteImport
      parentRoute: typeof EnLandlordsRegisterRoute
    }
  }
}

interface EnLandlordsRegisterRouteChildren {
  EnLandlordsRegisterPreviewRoute: typeof EnLandlordsRegisterPreviewRoute
  EnLandlordsRegisterPropertyRoute: typeof EnLandlordsRegisterPropertyRoute
  EnLandlordsRegisterRoomsRoute: typeof EnLandlordsRegisterRoomsRoute
  EnLandlordsRegisterTermsRoute: typeof EnLandlordsRegisterTermsRoute
}

const EnLandlordsRegisterRouteChildren: EnLandlordsRegisterRouteChildren = {
  EnLandlordsRegisterPreviewRoute: EnLandlordsRegisterPreviewRoute,
  EnLandlordsRegisterPropertyRoute: EnLandlordsRegisterPropertyRoute,
  EnLandlordsRegisterRoomsRoute: EnLandlordsRegisterRoomsRoute,
  EnLandlordsRegisterTermsRoute: EnLandlordsRegisterTermsRoute,
}

const EnLandlordsRegisterRouteWithChildren =
  EnLandlordsRegisterRoute._addFileChildren(EnLandlordsRegisterRouteChildren)

interface EnLandlordsRouteChildren {
  EnLandlordsGuideRoute: typeof EnLandlordsGuideRoute
  EnLandlordsRegisterRoute: typeof EnLandlordsRegisterRouteWithChildren
}

const EnLandlordsRouteChildren: EnLandlordsRouteChildren = {
  EnLandlordsGuideRoute: EnLandlordsGuideRoute,
  EnLandlordsRegisterRoute: EnLandlordsRegisterRouteWithChildren,
}

const EnLandlordsRouteWithChildren = EnLandlordsRoute._addFileChildren(
  EnLandlordsRouteChildren,
)

interface EnRouteChildren {
  EnAboutRoute: typeof EnAboutRoute
  EnApplyRoute: typeof EnApplyRoute
  EnChecklistRoute: typeof EnChecklistRoute
  EnContactRoute: typeof EnContactRoute
  EnLandlordsRoute: typeof EnLandlordsRouteWithChildren
  EnListingsRoute: typeof EnListingsRoute
  EnLoginRoute: typeof EnLoginRoute
  EnSignupRoute: typeof EnSignupRoute
  EnIndexRoute: typeof EnIndexRoute
}

const EnRouteChildren: EnRouteChildren = {
  EnAboutRoute: EnAboutRoute,
  EnApplyRoute: EnApplyRoute,
  EnChecklistRoute: EnChecklistRoute,
  EnContactRoute: EnContactRoute,
  EnLandlordsRoute: EnLandlordsRouteWithChildren,
  EnListingsRoute: EnListingsRoute,
  EnLoginRoute: EnLoginRoute,
  EnSignupRoute: EnSignupRoute,
  EnIndexRoute: EnIndexRoute,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

interface FrLandlordsRegisterRouteChildren {
  FrLandlordsRegisterPreviewRoute: typeof FrLandlordsRegisterPreviewRoute
  FrLandlordsRegisterPropertyRoute: typeof FrLandlordsRegisterPropertyRoute
  FrLandlordsRegisterRoomsRoute: typeof FrLandlordsRegisterRoomsRoute
  FrLandlordsRegisterTermsRoute: typeof FrLandlordsRegisterTermsRoute
}

const FrLandlordsRegisterRouteChildren: FrLandlordsRegisterRouteChildren = {
  FrLandlordsRegisterPreviewRoute: FrLandlordsRegisterPreviewRoute,
  FrLandlordsRegisterPropertyRoute: FrLandlordsRegisterPropertyRoute,
  FrLandlordsRegisterRoomsRoute: FrLandlordsRegisterRoomsRoute,
  FrLandlordsRegisterTermsRoute: FrLandlordsRegisterTermsRoute,
}

const FrLandlordsRegisterRouteWithChildren =
  FrLandlordsRegisterRoute._addFileChildren(FrLandlordsRegisterRouteChildren)

interface FrLandlordsRouteChildren {
  FrLandlordsGuideRoute: typeof FrLandlordsGuideRoute
  FrLandlordsRegisterRoute: typeof FrLandlordsRegisterRouteWithChildren
}

const FrLandlordsRouteChildren: FrLandlordsRouteChildren = {
  FrLandlordsGuideRoute: FrLandlordsGuideRoute,
  FrLandlordsRegisterRoute: FrLandlordsRegisterRouteWithChildren,
}

const FrLandlordsRouteWithChildren = FrLandlordsRoute._addFileChildren(
  FrLandlordsRouteChildren,
)

interface FrRouteChildren {
  FrAboutRoute: typeof FrAboutRoute
  FrApplyRoute: typeof FrApplyRoute
  FrChecklistRoute: typeof FrChecklistRoute
  FrContactRoute: typeof FrContactRoute
  FrLandlordsRoute: typeof FrLandlordsRouteWithChildren
  FrListingsRoute: typeof FrListingsRoute
  FrLoginRoute: typeof FrLoginRoute
  FrSignupRoute: typeof FrSignupRoute
  FrIndexRoute: typeof FrIndexRoute
}

const FrRouteChildren: FrRouteChildren = {
  FrAboutRoute: FrAboutRoute,
  FrApplyRoute: FrApplyRoute,
  FrChecklistRoute: FrChecklistRoute,
  FrContactRoute: FrContactRoute,
  FrLandlordsRoute: FrLandlordsRouteWithChildren,
  FrListingsRoute: FrListingsRoute,
  FrLoginRoute: FrLoginRoute,
  FrSignupRoute: FrSignupRoute,
  FrIndexRoute: FrIndexRoute,
}

const FrRouteWithChildren = FrRoute._addFileChildren(FrRouteChildren)

interface KoContactBoardRouteChildren {
  KoContactBoardPostIdRoute: typeof KoContactBoardPostIdRoute
  KoContactBoardWriteRoute: typeof KoContactBoardWriteRoute
}

const KoContactBoardRouteChildren: KoContactBoardRouteChildren = {
  KoContactBoardPostIdRoute: KoContactBoardPostIdRoute,
  KoContactBoardWriteRoute: KoContactBoardWriteRoute,
}

const KoContactBoardRouteWithChildren = KoContactBoardRoute._addFileChildren(
  KoContactBoardRouteChildren,
)

interface KoContactRouteChildren {
  KoContactBoardRoute: typeof KoContactBoardRouteWithChildren
}

const KoContactRouteChildren: KoContactRouteChildren = {
  KoContactBoardRoute: KoContactBoardRouteWithChildren,
}

const KoContactRouteWithChildren = KoContactRoute._addFileChildren(
  KoContactRouteChildren,
)

interface KoLandlordsRegisterRouteChildren {
  KoLandlordsRegisterPreviewRoute: typeof KoLandlordsRegisterPreviewRoute
  KoLandlordsRegisterPropertyRoute: typeof KoLandlordsRegisterPropertyRoute
  KoLandlordsRegisterRoomsRoute: typeof KoLandlordsRegisterRoomsRoute
  KoLandlordsRegisterTermsRoute: typeof KoLandlordsRegisterTermsRoute
}

const KoLandlordsRegisterRouteChildren: KoLandlordsRegisterRouteChildren = {
  KoLandlordsRegisterPreviewRoute: KoLandlordsRegisterPreviewRoute,
  KoLandlordsRegisterPropertyRoute: KoLandlordsRegisterPropertyRoute,
  KoLandlordsRegisterRoomsRoute: KoLandlordsRegisterRoomsRoute,
  KoLandlordsRegisterTermsRoute: KoLandlordsRegisterTermsRoute,
}

const KoLandlordsRegisterRouteWithChildren =
  KoLandlordsRegisterRoute._addFileChildren(KoLandlordsRegisterRouteChildren)

interface KoLandlordsRouteChildren {
  KoLandlordsGuideRoute: typeof KoLandlordsGuideRoute
  KoLandlordsRegisterRoute: typeof KoLandlordsRegisterRouteWithChildren
}

const KoLandlordsRouteChildren: KoLandlordsRouteChildren = {
  KoLandlordsGuideRoute: KoLandlordsGuideRoute,
  KoLandlordsRegisterRoute: KoLandlordsRegisterRouteWithChildren,
}

const KoLandlordsRouteWithChildren = KoLandlordsRoute._addFileChildren(
  KoLandlordsRouteChildren,
)

interface KoRouteChildren {
  KoAboutRoute: typeof KoAboutRoute
  KoApplyRoute: typeof KoApplyRoute
  KoChecklistRoute: typeof KoChecklistRoute
  KoContactRoute: typeof KoContactRouteWithChildren
  KoLandlordsRoute: typeof KoLandlordsRouteWithChildren
  KoListingsRoute: typeof KoListingsRoute
  KoLoginRoute: typeof KoLoginRoute
  KoSignupRoute: typeof KoSignupRoute
  KoIndexRoute: typeof KoIndexRoute
}

const KoRouteChildren: KoRouteChildren = {
  KoAboutRoute: KoAboutRoute,
  KoApplyRoute: KoApplyRoute,
  KoChecklistRoute: KoChecklistRoute,
  KoContactRoute: KoContactRouteWithChildren,
  KoLandlordsRoute: KoLandlordsRouteWithChildren,
  KoListingsRoute: KoListingsRoute,
  KoLoginRoute: KoLoginRoute,
  KoSignupRoute: KoSignupRoute,
  KoIndexRoute: KoIndexRoute,
}

const KoRouteWithChildren = KoRoute._addFileChildren(KoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  EnRoute: EnRouteWithChildren,
  FrRoute: FrRouteWithChildren,
  KoRoute: KoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
